ALTER SESSION SET NLS_TIMESTAMP_FORMAT = 'YYYY-MM-DD HH24:MI:SS.FF6';
ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS';

CREATE TABLE ASSESSMENT_SESSION
(
    SESSION_ID                  VARCHAR2(40)                                NOT NULL,
    COURSE_YEAR                 VARCHAR2(4)                          NOT NULL,
    COURSE_MONTH                VARCHAR2(2)                          NOT NULL,
    SCHOOL_YEAR                 VARCHAR2(10)                         NOT NULL,
    ACTIVE_FROM_DATE            TIMESTAMP                           NOT NULL,
    ACTIVE_UNTIL_DATE           TIMESTAMP                           NOT NULL,
    CREATE_USER                 VARCHAR(100)                        NOT NULL,
    CREATE_DATE                 TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER                 VARCHAR(100)                        NOT NULL,
    UPDATE_DATE                 TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT SESSION_ID_PK PRIMARY KEY (SESSION_ID)
);

INSERT INTO ASSESSMENT_SESSION (SESSION_ID, COURSE_YEAR, COURSE_MONTH, SCHOOL_YEAR, ACTIVE_FROM_DATE,
                                ACTIVE_UNTIL_DATE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')),
        '2018', '01', '2017/2018',
        to_date('2017-10-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2018-02-28 00:00:00','YYYY-MM-DD HH24:MI:SS'),
        'ASSESSMENT-API', CURRENT_TIMESTAMP,'ASSESSMENT-API',CURRENT_TIMESTAMP);

INSERT INTO ASSESSMENT_SESSION (SESSION_ID, COURSE_YEAR, COURSE_MONTH, SCHOOL_YEAR, ACTIVE_FROM_DATE,
                                ACTIVE_UNTIL_DATE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')),
        '2018', '04', '2017/2018',
        to_date('2017-10-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2018-04-30 00:00:00','YYYY-MM-DD HH24:MI:SS'),
        'ASSESSMENT-API', CURRENT_TIMESTAMP,'ASSESSMENT-API',CURRENT_TIMESTAMP);

INSERT INTO ASSESSMENT_SESSION (SESSION_ID, COURSE_YEAR, COURSE_MONTH, SCHOOL_YEAR, ACTIVE_FROM_DATE,
                                ACTIVE_UNTIL_DATE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')),
        '2018', '06', '2017/2018',
        to_date('2017-10-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2018-06-30 00:00:00','YYYY-MM-DD HH24:MI:SS'),
        'ASSESSMENT-API', CURRENT_TIMESTAMP,'ASSESSMENT-API',CURRENT_TIMESTAMP);

INSERT INTO ASSESSMENT_SESSION (SESSION_ID, COURSE_YEAR, COURSE_MONTH, SCHOOL_YEAR, ACTIVE_FROM_DATE,
                                ACTIVE_UNTIL_DATE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')),
        '2018', '11', '2018/2019',
        to_date('2018-10-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2018-11-30 00:00:00','YYYY-MM-DD HH24:MI:SS'),
        'ASSESSMENT-API', CURRENT_TIMESTAMP,'ASSESSMENT-API',CURRENT_TIMESTAMP);

INSERT INTO ASSESSMENT_SESSION (SESSION_ID, COURSE_YEAR, COURSE_MONTH, SCHOOL_YEAR, ACTIVE_FROM_DATE,
                                ACTIVE_UNTIL_DATE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')),
        '2019', '01', '2018/2019',
        to_date('2018-10-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2019-02-28 00:00:00','YYYY-MM-DD HH24:MI:SS'),
        'ASSESSMENT-API', CURRENT_TIMESTAMP,'ASSESSMENT-API',CURRENT_TIMESTAMP);

INSERT INTO ASSESSMENT_SESSION (SESSION_ID, COURSE_YEAR, COURSE_MONTH, SCHOOL_YEAR, ACTIVE_FROM_DATE,
                                ACTIVE_UNTIL_DATE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')),
        '2019', '04', '2018/2019',
        to_date('2018-10-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2019-04-30 00:00:00','YYYY-MM-DD HH24:MI:SS'),
        'ASSESSMENT-API', CURRENT_TIMESTAMP,'ASSESSMENT-API',CURRENT_TIMESTAMP);

INSERT INTO ASSESSMENT_SESSION (SESSION_ID, COURSE_YEAR, COURSE_MONTH, SCHOOL_YEAR, ACTIVE_FROM_DATE,
                                ACTIVE_UNTIL_DATE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')),
        '2019', '06', '2018/2019',
        to_date('2018-10-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2019-06-30 00:00:00','YYYY-MM-DD HH24:MI:SS'),
        'ASSESSMENT-API', CURRENT_TIMESTAMP,'ASSESSMENT-API',CURRENT_TIMESTAMP);

INSERT INTO ASSESSMENT_SESSION (SESSION_ID, COURSE_YEAR, COURSE_MONTH, SCHOOL_YEAR, ACTIVE_FROM_DATE,
                                ACTIVE_UNTIL_DATE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')),
        '2019', '11', '2019/2020',
        to_date('2019-10-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2019-11-30 00:00:00','YYYY-MM-DD HH24:MI:SS'),
        'ASSESSMENT-API', CURRENT_TIMESTAMP,'ASSESSMENT-API',CURRENT_TIMESTAMP);

INSERT INTO ASSESSMENT_SESSION (SESSION_ID, COURSE_YEAR, COURSE_MONTH, SCHOOL_YEAR, ACTIVE_FROM_DATE,
                                ACTIVE_UNTIL_DATE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')),
        '2020', '01', '2019/2020',
        to_date('2019-10-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2020-02-28 00:00:00','YYYY-MM-DD HH24:MI:SS'),
        'ASSESSMENT-API', CURRENT_TIMESTAMP,'ASSESSMENT-API',CURRENT_TIMESTAMP);

INSERT INTO ASSESSMENT_SESSION (SESSION_ID, COURSE_YEAR, COURSE_MONTH, SCHOOL_YEAR, ACTIVE_FROM_DATE,
                                ACTIVE_UNTIL_DATE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')),
        '2020', '04', '2019/2020',
        to_date('2019-10-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2020-04-30 00:00:00','YYYY-MM-DD HH24:MI:SS'),
        'ASSESSMENT-API', CURRENT_TIMESTAMP,'ASSESSMENT-API',CURRENT_TIMESTAMP);

INSERT INTO ASSESSMENT_SESSION (SESSION_ID, COURSE_YEAR, COURSE_MONTH, SCHOOL_YEAR, ACTIVE_FROM_DATE,
                                ACTIVE_UNTIL_DATE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')),
        '2020', '06', '2019/2020',
        to_date('2019-10-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2020-06-30 00:00:00','YYYY-MM-DD HH24:MI:SS'),
        'ASSESSMENT-API', CURRENT_TIMESTAMP,'ASSESSMENT-API',CURRENT_TIMESTAMP);

INSERT INTO ASSESSMENT_SESSION (SESSION_ID, COURSE_YEAR, COURSE_MONTH, SCHOOL_YEAR, ACTIVE_FROM_DATE,
                                ACTIVE_UNTIL_DATE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')),
        '2020', '11', '2020/2021',
        to_date('2020-10-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2020-11-30 00:00:00','YYYY-MM-DD HH24:MI:SS'),
        'ASSESSMENT-API', CURRENT_TIMESTAMP,'ASSESSMENT-API',CURRENT_TIMESTAMP);

INSERT INTO ASSESSMENT_SESSION (SESSION_ID, COURSE_YEAR, COURSE_MONTH, SCHOOL_YEAR, ACTIVE_FROM_DATE,
                                ACTIVE_UNTIL_DATE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')),
        '2021', '01', '2020/2021',
        to_date('2020-10-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2021-02-28 00:00:00','YYYY-MM-DD HH24:MI:SS'),
        'ASSESSMENT-API', CURRENT_TIMESTAMP,'ASSESSMENT-API',CURRENT_TIMESTAMP);

INSERT INTO ASSESSMENT_SESSION (SESSION_ID, COURSE_YEAR, COURSE_MONTH, SCHOOL_YEAR, ACTIVE_FROM_DATE,
                                ACTIVE_UNTIL_DATE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')),
        '2021', '04', '2020/2021',
        to_date('2020-10-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2021-04-30 00:00:00','YYYY-MM-DD HH24:MI:SS'),
        'ASSESSMENT-API', CURRENT_TIMESTAMP,'ASSESSMENT-API',CURRENT_TIMESTAMP);

INSERT INTO ASSESSMENT_SESSION (SESSION_ID, COURSE_YEAR, COURSE_MONTH, SCHOOL_YEAR, ACTIVE_FROM_DATE,
                                ACTIVE_UNTIL_DATE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')),
        '2021', '06', '2020/2021',
        to_date('2020-10-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2021-06-30 00:00:00','YYYY-MM-DD HH24:MI:SS'),
        'ASSESSMENT-API', CURRENT_TIMESTAMP,'ASSESSMENT-API',CURRENT_TIMESTAMP);

INSERT INTO ASSESSMENT_SESSION (SESSION_ID, COURSE_YEAR, COURSE_MONTH, SCHOOL_YEAR, ACTIVE_FROM_DATE,
                                ACTIVE_UNTIL_DATE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')),
        '2021', '11', '2021/2022',
        to_date('2021-10-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2021-11-30 00:00:00','YYYY-MM-DD HH24:MI:SS'),
        'ASSESSMENT-API', CURRENT_TIMESTAMP,'ASSESSMENT-API',CURRENT_TIMESTAMP);

INSERT INTO ASSESSMENT_SESSION (SESSION_ID, COURSE_YEAR, COURSE_MONTH, SCHOOL_YEAR, ACTIVE_FROM_DATE,
                                ACTIVE_UNTIL_DATE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')),
        '2022', '01', '2021/2022',
        to_date('2021-10-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2022-02-28 00:00:00','YYYY-MM-DD HH24:MI:SS'),
        'ASSESSMENT-API', CURRENT_TIMESTAMP,'ASSESSMENT-API',CURRENT_TIMESTAMP);

INSERT INTO ASSESSMENT_SESSION (SESSION_ID, COURSE_YEAR, COURSE_MONTH, SCHOOL_YEAR, ACTIVE_FROM_DATE,
                                ACTIVE_UNTIL_DATE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')),
        '2022', '04', '2021/2022',
        to_date('2021-10-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2022-04-30 00:00:00','YYYY-MM-DD HH24:MI:SS'),
        'ASSESSMENT-API', CURRENT_TIMESTAMP,'ASSESSMENT-API',CURRENT_TIMESTAMP);

INSERT INTO ASSESSMENT_SESSION (SESSION_ID, COURSE_YEAR, COURSE_MONTH, SCHOOL_YEAR, ACTIVE_FROM_DATE,
                                ACTIVE_UNTIL_DATE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')),
        '2022', '06', '2021/2022',
        to_date('2021-10-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2022-06-30 00:00:00','YYYY-MM-DD HH24:MI:SS'),
        'ASSESSMENT-API', CURRENT_TIMESTAMP,'ASSESSMENT-API',CURRENT_TIMESTAMP);

INSERT INTO ASSESSMENT_SESSION (SESSION_ID, COURSE_YEAR, COURSE_MONTH, SCHOOL_YEAR, ACTIVE_FROM_DATE,
                                ACTIVE_UNTIL_DATE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')),
        '2022', '11', '2022/2023',
        to_date('2022-10-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2022-11-30 00:00:00','YYYY-MM-DD HH24:MI:SS'),
        'ASSESSMENT-API', CURRENT_TIMESTAMP,'ASSESSMENT-API',CURRENT_TIMESTAMP);

INSERT INTO ASSESSMENT_SESSION (SESSION_ID, COURSE_YEAR, COURSE_MONTH, SCHOOL_YEAR, ACTIVE_FROM_DATE,
                                ACTIVE_UNTIL_DATE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')),
        '2023', '01', '2022/2023',
        to_date('2022-10-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2023-02-28 00:00:00','YYYY-MM-DD HH24:MI:SS'),
        'ASSESSMENT-API', CURRENT_TIMESTAMP,'ASSESSMENT-API',CURRENT_TIMESTAMP);

INSERT INTO ASSESSMENT_SESSION (SESSION_ID, COURSE_YEAR, COURSE_MONTH, SCHOOL_YEAR, ACTIVE_FROM_DATE,
                                ACTIVE_UNTIL_DATE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')),
        '2023', '04', '2022/2023',
        to_date('2022-10-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2023-04-30 00:00:00','YYYY-MM-DD HH24:MI:SS'),
        'ASSESSMENT-API', CURRENT_TIMESTAMP,'ASSESSMENT-API',CURRENT_TIMESTAMP);

INSERT INTO ASSESSMENT_SESSION (SESSION_ID, COURSE_YEAR, COURSE_MONTH, SCHOOL_YEAR, ACTIVE_FROM_DATE,
                                ACTIVE_UNTIL_DATE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')),
        '2023', '06', '2022/2023',
        to_date('2022-10-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2023-06-30 00:00:00','YYYY-MM-DD HH24:MI:SS'),
        'ASSESSMENT-API', CURRENT_TIMESTAMP,'ASSESSMENT-API',CURRENT_TIMESTAMP);

INSERT INTO ASSESSMENT_SESSION (SESSION_ID, COURSE_YEAR, COURSE_MONTH, SCHOOL_YEAR, ACTIVE_FROM_DATE,
                                ACTIVE_UNTIL_DATE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')),
        '2023', '11', '2023/2024',
        to_date('2023-10-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2023-11-30 00:00:00','YYYY-MM-DD HH24:MI:SS'),
        'ASSESSMENT-API', CURRENT_TIMESTAMP,'ASSESSMENT-API',CURRENT_TIMESTAMP);

INSERT INTO ASSESSMENT_SESSION (SESSION_ID, COURSE_YEAR, COURSE_MONTH, SCHOOL_YEAR, ACTIVE_FROM_DATE,
                                ACTIVE_UNTIL_DATE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')),
        '2024', '01', '2023/2024',
        to_date('2023-10-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2024-02-28 00:00:00','YYYY-MM-DD HH24:MI:SS'),
        'ASSESSMENT-API', CURRENT_TIMESTAMP,'ASSESSMENT-API',CURRENT_TIMESTAMP);

INSERT INTO ASSESSMENT_SESSION (SESSION_ID, COURSE_YEAR, COURSE_MONTH, SCHOOL_YEAR, ACTIVE_FROM_DATE,
                                ACTIVE_UNTIL_DATE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')),
        '2024', '04', '2023/2024',
        to_date('2023-10-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2024-04-30 00:00:00','YYYY-MM-DD HH24:MI:SS'),
        'ASSESSMENT-API', CURRENT_TIMESTAMP,'ASSESSMENT-API',CURRENT_TIMESTAMP);

INSERT INTO ASSESSMENT_SESSION (SESSION_ID, COURSE_YEAR, COURSE_MONTH, SCHOOL_YEAR, ACTIVE_FROM_DATE,
                                ACTIVE_UNTIL_DATE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')),
        '2024', '06', '2023/2024',
        to_date('2023-10-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2024-06-30 00:00:00','YYYY-MM-DD HH24:MI:SS'),
        'ASSESSMENT-API', CURRENT_TIMESTAMP,'ASSESSMENT-API',CURRENT_TIMESTAMP);

INSERT INTO ASSESSMENT_SESSION (SESSION_ID, COURSE_YEAR, COURSE_MONTH, SCHOOL_YEAR, ACTIVE_FROM_DATE,
                                ACTIVE_UNTIL_DATE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')),
        '2024', '11', '2024/2025',
        to_date('2024-10-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2024-11-30 00:00:00','YYYY-MM-DD HH24:MI:SS'),
        'ASSESSMENT-API', CURRENT_TIMESTAMP,'ASSESSMENT-API',CURRENT_TIMESTAMP);

INSERT INTO ASSESSMENT_SESSION (SESSION_ID, COURSE_YEAR, COURSE_MONTH, SCHOOL_YEAR, ACTIVE_FROM_DATE,
                                ACTIVE_UNTIL_DATE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')),
        '2025', '01', '2024/2025',
        to_date('2024-10-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2025-02-28 00:00:00','YYYY-MM-DD HH24:MI:SS'),
        'ASSESSMENT-API', CURRENT_TIMESTAMP,'ASSESSMENT-API',CURRENT_TIMESTAMP);

INSERT INTO ASSESSMENT_SESSION (SESSION_ID, COURSE_YEAR, COURSE_MONTH, SCHOOL_YEAR, ACTIVE_FROM_DATE,
                                ACTIVE_UNTIL_DATE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')),
        '2025', '04', '2024/2025',
        to_date('2024-10-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2025-04-30 00:00:00','YYYY-MM-DD HH24:MI:SS'),
        'ASSESSMENT-API', CURRENT_TIMESTAMP,'ASSESSMENT-API',CURRENT_TIMESTAMP);

INSERT INTO ASSESSMENT_SESSION (SESSION_ID, COURSE_YEAR, COURSE_MONTH, SCHOOL_YEAR, ACTIVE_FROM_DATE,
                                ACTIVE_UNTIL_DATE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')),
        '2025', '06', '2024/2025',
        to_date('2024-10-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2025-06-30 00:00:00','YYYY-MM-DD HH24:MI:SS'),
        'ASSESSMENT-API', CURRENT_TIMESTAMP,'ASSESSMENT-API',CURRENT_TIMESTAMP);

INSERT INTO ASSESSMENT_SESSION (SESSION_ID, COURSE_YEAR, COURSE_MONTH, SCHOOL_YEAR, ACTIVE_FROM_DATE,
                                ACTIVE_UNTIL_DATE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')),
        '2025', '11', '2025/2026',
        to_date('2025-10-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2025-11-30 00:00:00','YYYY-MM-DD HH24:MI:SS'),
        'ASSESSMENT-API', CURRENT_TIMESTAMP,'ASSESSMENT-API',CURRENT_TIMESTAMP);

INSERT INTO ASSESSMENT_SESSION (SESSION_ID, COURSE_YEAR, COURSE_MONTH, SCHOOL_YEAR, ACTIVE_FROM_DATE,
                                ACTIVE_UNTIL_DATE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')),
        '2026', '01', '2025/2026',
        to_date('2025-10-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2026-02-28 00:00:00','YYYY-MM-DD HH24:MI:SS'),
        'ASSESSMENT-API', CURRENT_TIMESTAMP,'ASSESSMENT-API',CURRENT_TIMESTAMP);

INSERT INTO ASSESSMENT_SESSION (SESSION_ID, COURSE_YEAR, COURSE_MONTH, SCHOOL_YEAR, ACTIVE_FROM_DATE,
                                ACTIVE_UNTIL_DATE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')),
        '2026', '04', '2025/2026',
        to_date('2025-10-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2026-04-30 00:00:00','YYYY-MM-DD HH24:MI:SS'),
        'ASSESSMENT-API', CURRENT_TIMESTAMP,'ASSESSMENT-API',CURRENT_TIMESTAMP);

INSERT INTO ASSESSMENT_SESSION (SESSION_ID, COURSE_YEAR, COURSE_MONTH, SCHOOL_YEAR, ACTIVE_FROM_DATE,
                                ACTIVE_UNTIL_DATE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')),
        '2026', '06', '2025/2026',
        to_date('2025-10-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2026-06-30 00:00:00','YYYY-MM-DD HH24:MI:SS'),
        'ASSESSMENT-API', CURRENT_TIMESTAMP,'ASSESSMENT-API',CURRENT_TIMESTAMP);


assessment_id
session_id
assessment_type_code
create_user
create_date
update_user
update_date

CREATE TABLE ASSESSMENT
as
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as ASSESSMENT_ID,
    (SELECT SESSION_ID FROM ASSESSMENT_SESSION sess WHERE sess.COURSE_YEAR = grad_assmnt. AND sess.COURSE_MONTH = ) AS COLLECTION_ID,
    'ASSESSMENT-API' as CREATE_USER,
    CURRENT_TIMESTAMP as CREATE_DATE,
    'ASSESSMENT-API' as UPDATE_USER,
    CURRENT_TIMESTAMP as UPDATE_DATE
FROM TAB_GRAD_ASSMT grad_assmnt;
