CREATE TABLE EAS_EVENT
(
    EVENT_ID      UUID                               NOT NULL,
    EVENT_PAYLOAD BYTEA                              NOT NULL,
    EVENT_STATUS  VARCHAR(50)                        NOT NULL,
    EVENT_TYPE    VARCHAR(100)                       NOT NULL,
    SAGA_ID       UUID,
    EVENT_OUTCOME VARCHAR(100)                       NOT NULL,
    REPLY_CHANNEL VARCHAR(100),
    CREATE_USER   VARCHAR(100)                        NOT NULL,
    CREATE_DATE   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER   VARCHAR(100)                        NOT NULL,
    UPDATE_DATE   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT EAS_EVENT_EVENT_PK PRIMARY KEY (EVENT_ID)
);

CREATE INDEX EAS_EVENT_STATUS_IDX ON EAS_EVENT (EVENT_STATUS);
CREATE INDEX EAS_EVENT_TYPE_IDX ON EAS_EVENT (EVENT_TYPE);
