ALTER TABLE ASSESSMENT_STUDENT
ADD COLUMN SURNAME VARCHAR(255) NOT NULL;

ALTER TABLE ASSESSMENT_STUDENT
ADD COLUMN ASSESSMENT_CENTER  UUID NOT NULL;

ALTER TABLE ASSESSMENT_STUDENT_HISTORY
ADD COLUMN SURNAME  VARCHAR(255) NOT NULL;

ALTER TABLE ASSESSMENT_STUDENT_HISTORY
ADD COLUMN ASSESSMENT_CENTER  UUID NOT NULL;