ALTER TABLE ASSESSMENT_SESSION DROP COLUMN COURSE_SESSION;
ALTER TABLE ASSESSMENT_SESSION RENAME COLUMN STATUS_CODE TO SCHOOL_YEAR;
ALTER TABLE ASSESSMENT_SESSION DROP CONSTRAINT FK_STATUS_CODE;
DROP TABLE STATUS_CODE;
ALTER TABLE STUDENT_STATUS_CODE RENAME TO COURSE_STATUS_CODE;
ALTER TABLE COURSE_STATUS_CODE RENAME COLUMN STUDENT_STATUS_CODE TO COURSE_STATUS_CODE;
