CREATE TABLE ASSESSMENT_SESSION
(
    ASSESSMENT_SESSION_ID       UUID                                NOT NULL,
    COURSE_SESSION              VARCHAR(6)                          NOT NULL,
    COURSE_YEAR                 VARCHAR(4)                          NOT NULL,
    COURSE_MONTH                VARCHAR(2)                          NOT NULL,
    STATUS_CODE                 VARCHAR(10)                         NOT NULL,
    ACTIVE_FROM_DATE            TIMESTAMP                           NOT NULL,
    ACTIVE_UNTIL_DATE           TIMESTAMP                           NOT NULL,
    CREATE_USER                 VARCHAR(32)                         NOT NULL,
    CREATE_DATE                 TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER                 VARCHAR(32)                         NOT NULL,
    UPDATE_DATE                 TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ASSESSMENT_SESSION_ID_PK PRIMARY KEY (ASSESSMENT_SESSION_ID)
);

CREATE TABLE ASSESSMENT
(
    ASSESSMENT_ID                   UUID                                NOT NULL,
    ASSESSMENT_SESSION_ID           UUID                                NOT NULL,
    ASSESSMENT_TYPE_CODE            VARCHAR(10)                         NOT NULL,
    SCHOOL_ID                       UUID                                NOT NULL,
    STUDENT_ID                      UUID                                NOT NULL,
    PEN                             VARCHAR(9)                          NOT NULL,
    LOCAL_ID                        VARCHAR(12),
    IS_ELECTRONIC_EXAM              BOOLEAN,
    FINAL_PERCENTAGE                VARCHAR(3),
    PROVINCIAL_SPECIAL_CASE_CODE    VARCHAR(1),
    COURSE_STATUS_CODE              VARCHAR(1),
    CREATE_USER                     VARCHAR(32)                         NOT NULL,
    CREATE_DATE                     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER                     VARCHAR(32)                         NOT NULL,
    UPDATE_DATE                     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ASSESSMENT_ID_PK PRIMARY KEY (ASSESSMENT_ID)
);

CREATE TABLE ASSESSMENT_TYPE_CODE
(
    ASSESSMENT_TYPE_CODE VARCHAR(10)                            NOT NULL,
    LABEL                VARCHAR(50)                            NOT NULL,
    DESCRIPTION          VARCHAR(255)                           NOT NULL,
    DISPLAY_ORDER        NUMERIC   DEFAULT 1                    NOT NULL,
    EFFECTIVE_DATE       TIMESTAMP                              NOT NULL,
    EXPIRY_DATE          TIMESTAMP                              NOT NULL,
    CREATE_USER          VARCHAR(32)                            NOT NULL,
    CREATE_DATE          TIMESTAMP DEFAULT CURRENT_TIMESTAMP    NOT NULL,
    UPDATE_USER          VARCHAR(32)                            NOT NULL,
    UPDATE_DATE          TIMESTAMP DEFAULT CURRENT_TIMESTAMP    NOT NULL,
    CONSTRAINT ASSESSMENT_TYPE_CODE_PK PRIMARY KEY (ASSESSMENT_TYPE_CODE)
);

ALTER TABLE ASSESSMENT
    ADD CONSTRAINT FK_ASSESSMENT_TYPE_CODE FOREIGN KEY (ASSESSMENT_TYPE_CODE)
        REFERENCES ASSESSMENT_TYPE_CODE (ASSESSMENT_TYPE_CODE);

ALTER TABLE ASSESSMENT
    ADD CONSTRAINT FK_ASSESSMENT_SESSION_ID FOREIGN KEY (ASSESSMENT_SESSION_ID)
        REFERENCES ASSESSMENT_SESSION (ASSESSMENT_SESSION_ID);

INSERT INTO ASSESSMENT_TYPE_CODE (ASSESSMENT_TYPE_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE)
    VALUES ('LTE10','Literacy 10 Assessment','Literacy 10 Assessment',10,
            to_date('2019-07-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            to_date('2099-12-31 00:00:00','YYYY-MM-DD HH24:MI:SS'),
            'EAS-API', CURRENT_TIMESTAMP,'EAS-API',CURRENT_TIMESTAMP);

INSERT INTO ASSESSMENT_TYPE_CODE (ASSESSMENT_TYPE_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE)
    VALUES ('LTE12','Literacy 12 Assessment','Literacy 12 Assessment',20,
            to_date('2021-07-01 00:00:00','YYYY-MM-DD HH24:MI:SS'),
            to_date('2099-12-31 00:00:00','YYYY-MM-DD HH24:MI:SS'),
            'EAS-API', CURRENT_TIMESTAMP,'EAS-API',CURRENT_TIMESTAMP);

INSERT INTO ASSESSMENT_TYPE_CODE (ASSESSMENT_TYPE_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE)
    VALUES ('LTF12','Évaluation de littératie 12 – immersion','Évaluation de littératie 12 – immersion',30,
            to_date('2021-07-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            to_date('2099-12-31 00:00:00','YYYY-MM-DD HH24:MI:SS'),
            'EAS-API', CURRENT_TIMESTAMP,'EAS-API',CURRENT_TIMESTAMP);

INSERT INTO ASSESSMENT_TYPE_CODE (ASSESSMENT_TYPE_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE)
    VALUES ('LTP10','Évaluation de littératie 10 – langue première','Évaluation de littératie 10 – langue première',40,
            to_date('2019-07-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            to_date('2099-12-31 00:00:00','YYYY-MM-DD HH24:MI:SS'),
            'EAS-API', CURRENT_TIMESTAMP,'EAS-API',CURRENT_TIMESTAMP);

INSERT INTO ASSESSMENT_TYPE_CODE (ASSESSMENT_TYPE_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE)
    VALUES ('LTP12','Évaluation de littératie 12 – langue première','Évaluation de littératie 12 – langue première',50,
            to_date('2021-07-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            to_date('2099-12-31 00:00:00','YYYY-MM-DD HH24:MI:SS'),
            'EAS-API', CURRENT_TIMESTAMP,'EAS-API',CURRENT_TIMESTAMP);

INSERT INTO ASSESSMENT_TYPE_CODE (ASSESSMENT_TYPE_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE)
    VALUES ('NME','Numeracy Assessment','Numeracy Assessment',60,
            to_date('2017-10-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            to_date('2019-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            'EAS-API', CURRENT_TIMESTAMP,'EAS-API',CURRENT_TIMESTAMP);

INSERT INTO ASSESSMENT_TYPE_CODE (ASSESSMENT_TYPE_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE)
    VALUES ('NME10','Numeracy 10 Assessment','Numeracy 10 Assessment',70,
            to_date('2019-07-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            to_date('2099-12-31 00:00:00','YYYY-MM-DD HH24:MI:SS'),
            'EAS-API', CURRENT_TIMESTAMP,'EAS-API',CURRENT_TIMESTAMP);

INSERT INTO ASSESSMENT_TYPE_CODE (ASSESSMENT_TYPE_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE)
    VALUES ('NMF','Évaluation de numératie','Évaluation de numératie',80,
            to_date('2017-10-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            to_date('2019-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            'EAS-API', CURRENT_TIMESTAMP,'EAS-API',CURRENT_TIMESTAMP);

INSERT INTO ASSESSMENT_TYPE_CODE (ASSESSMENT_TYPE_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE)
    VALUES ('NMF10','Évaluation de numératie 10','Évaluation de numératie 10',90,
            to_date('2019-07-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            to_date('2099-12-31 00:00:00','YYYY-MM-DD HH24:MI:SS'),
            'EAS-API', CURRENT_TIMESTAMP,'EAS-API',CURRENT_TIMESTAMP);