ALTER TABLE ASSESSMENT_STUDENT ADD CONSTRAINT assessment_id_fk FOREIGN KEY (ASSESSMENT_ID ) REFERENCES ASSESSMENT (ASSESSMENT_ID);

ALTER TABLE ASSESSMENT ADD CONSTRAINT session_id_fk FOREIGN KEY (SESSION_ID) REFERENCES ASSESSMENT_SESSION (SESSION_ID);