ALTER TABLE ASSESSMENT_STUDENT_HISTORY DROP COLUMN FINAL_PERCENTAGE;
ALTER TABLE ASSESSMENT_STUDENT_HISTORY ADD COLUMN PROFICIENCY_SCORE NUMERIC(1,0);

ALTER TABLE ASSESSMENT_STUDENT
ADD COLUMN NUMBER_OF_ATTEMPTS NUMERIC(1,0) NULL;

ALTER TABLE ASSESSMENT_STUDENT_HISTORY
ADD COLUMN NUMBER_OF_ATTEMPTS NUMERIC(1,0) NULL;
