CREATE TABLE COGN_LEVEL_CODE
(
    COGN_LEVEL_CODE             VARCHAR(10)                         NOT NULL,
    LABEL                       VARCHAR(255)                        NOT NULL,
    DESCRIPTION                 VARCHAR(255)                        NOT NULL,
    DISPLAY_ORDER               INTEGER DEFAULT 10                  NOT NULL,
    EFFECTIVE_DATE              TIMESTAMP                           NOT NULL,
    EXPIRY_DATE                 TIMESTAMP                           NOT NULL,
    CREATE_USER                 VARCHAR(100)                        NOT NULL,
    CREATE_DATE                 TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER                 VARCHAR(100)                        NOT NULL,
    UPDATE_DATE                 TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT COGN_LEVEL_CODE_PK PRIMARY KEY (COGN_LEVEL_CODE)
);

CREATE TABLE TASK_CODE
(
    TASK_CODE                   VARCHAR(10)                         NOT NULL,
    LABEL                       VARCHAR(255)                        NOT NULL,
    DESCRIPTION                 VARCHAR(255)                        NOT NULL,
    DISPLAY_ORDER               INTEGER DEFAULT 10                  NOT NULL,
    EFFECTIVE_DATE              TIMESTAMP                           NOT NULL,
    EXPIRY_DATE                 TIMESTAMP                           NOT NULL,
    CREATE_USER                 VARCHAR(100)                        NOT NULL,
    CREATE_DATE                 TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER                 VARCHAR(100)                        NOT NULL,
    UPDATE_DATE                 TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT TASK_CODE_PK PRIMARY KEY (TASK_CODE)
);

CREATE TABLE CLAIM_CODE
(
    CLAIM_CODE                  VARCHAR(10)                         NOT NULL,
    LABEL                       VARCHAR(255)                        NOT NULL,
    DESCRIPTION                 VARCHAR(255)                        NOT NULL,
    DISPLAY_ORDER               INTEGER DEFAULT 10                  NOT NULL,
    EFFECTIVE_DATE              TIMESTAMP                           NOT NULL,
    EXPIRY_DATE                 TIMESTAMP                           NOT NULL,
    CREATE_USER                 VARCHAR(100)                        NOT NULL,
    CREATE_DATE                 TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER                 VARCHAR(100)                        NOT NULL,
    UPDATE_DATE                 TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT CLAIM_CODE_PK PRIMARY KEY (CLAIM_CODE)
);

CREATE TABLE CONTEXT_CODE
(
    CONTEXT_CODE                VARCHAR(10)                          NOT NULL,
    LABEL                       VARCHAR(255)                        NOT NULL,
    DESCRIPTION                 VARCHAR(255)                        NOT NULL,
    DISPLAY_ORDER               INTEGER DEFAULT 10                  NOT NULL,
    EFFECTIVE_DATE              TIMESTAMP                           NOT NULL,
    EXPIRY_DATE                 TIMESTAMP                           NOT NULL,
    CREATE_USER                 VARCHAR(100)                        NOT NULL,
    CREATE_DATE                 TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER                 VARCHAR(100)                        NOT NULL,
    UPDATE_DATE                 TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT CONTEXT_CODE_PK PRIMARY KEY (CONTEXT_CODE)
);

CREATE TABLE CONCEPT_CODE
(
    CONCEPT_CODE                VARCHAR(10)                         NOT NULL,
    LABEL                       VARCHAR(255)                        NOT NULL,
    DESCRIPTION                 VARCHAR(255)                        NOT NULL,
    DISPLAY_ORDER               INTEGER DEFAULT 10                  NOT NULL,
    EFFECTIVE_DATE              TIMESTAMP                           NOT NULL,
    EXPIRY_DATE                 TIMESTAMP                           NOT NULL,
    CREATE_USER                 VARCHAR(100)                        NOT NULL,
    CREATE_DATE                 TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER                 VARCHAR(100)                        NOT NULL,
    UPDATE_DATE                 TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT CONCEPT_CODE_PK PRIMARY KEY (CONCEPT_CODE)
);

CREATE TABLE ASSESSMENT_FORM
(
    ASSESSMENT_FORM_ID          UUID                                NOT NULL,
    ASSESSMENT_ID               UUID                                NOT NULL,
    FORM_CODE                   VARCHAR(1)                          NOT NULL,
    CREATE_USER                 VARCHAR(100)                        NOT NULL,
    CREATE_DATE                 TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER                 VARCHAR(100)                        NOT NULL,
    UPDATE_DATE                 TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ASSESSMENT_FORM_ID_PK PRIMARY KEY (ASSESSMENT_FORM_ID),
    CONSTRAINT FK_ASSESSMENT_ID FOREIGN KEY (ASSESSMENT_ID)
        REFERENCES ASSESSMENT (ASSESSMENT_ID)
);

CREATE TABLE ASSESSMENT_QUESTION
(
    ASSESSMENT_QUESTION_ID      UUID                                NOT NULL,
    ASSESSMENT_FORM_ID          UUID                                NOT NULL,
    QUES_NUMBER                 INTEGER                             NOT NULL,
    ITEM_TYPE                   VARCHAR(12)                         NOT NULL,
    MARK_VALUE                  INTEGER                             NOT NULL,
    COGN_LEVEL_CODE             VARCHAR(10)                                  ,
    TASK_CODE                   VARCHAR(10)                                  ,
    CLAIM_CODE                  VARCHAR(10)                                  ,
    CONTEXT_CODE                VARCHAR(10)                                  ,
    CONCEPT_CODE                VARCHAR(10)                                  ,
    SCALE_FACTOR                NUMERIC                             NOT NULL,
    ASSMT_SECTION               VARCHAR(8)                          NOT NULL,
    CREATE_USER                 VARCHAR(100)                        NOT NULL,
    CREATE_DATE                 TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER                 VARCHAR(100)                        NOT NULL,
    UPDATE_DATE                 TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ASSESSMENT_QUESTION_ID_PK PRIMARY KEY (ASSESSMENT_QUESTION_ID),
    CONSTRAINT FK_ASSESSMENT_FORM_ID FOREIGN KEY (ASSESSMENT_FORM_ID)
        REFERENCES ASSESSMENT_FORM (ASSESSMENT_FORM_ID),
    CONSTRAINT FK_COGN_LEVEL_CODE FOREIGN KEY (COGN_LEVEL_CODE)
        REFERENCES COGN_LEVEL_CODE (COGN_LEVEL_CODE),
    CONSTRAINT FK_TASK_CODE FOREIGN KEY (TASK_CODE)
        REFERENCES TASK_CODE (TASK_CODE),
    CONSTRAINT FK_CLAIM_CODE FOREIGN KEY (CLAIM_CODE)
        REFERENCES CLAIM_CODE (CLAIM_CODE),
    CONSTRAINT FK_CONTEXT_CODE FOREIGN KEY (CONTEXT_CODE)
        REFERENCES CONTEXT_CODE (CONTEXT_CODE),
    CONSTRAINT FK_CONCEPT_CODE FOREIGN KEY (CONCEPT_CODE)
        REFERENCES CONCEPT_CODE (CONCEPT_CODE)
);

CREATE TABLE ASSESSMENT_QUESTION_RESPONSE_OPTION
(
    ASSESSMENT_QUESTION_RESPONSE_OPTION_ID     UUID                 NOT NULL,
    ASSESSMENT_QUESTION_ID                     UUID                 NOT NULL,
    IS_CORRECT_ANSWER                          BOOLEAN              NOT NULL,
    CREATE_USER                                VARCHAR(100)         NOT NULL,
    CREATE_DATE                 TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER                                 VARCHAR(100)        NOT NULL,
    UPDATE_DATE                 TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ASSESSMENT_QUESTION_RESPONSE_OPTION_ID_PK PRIMARY KEY (ASSESSMENT_QUESTION_RESPONSE_OPTION_ID),
    CONSTRAINT FK_ASSESSMENT_QUESTION_ID FOREIGN KEY (ASSESSMENT_QUESTION_ID)
        REFERENCES ASSESSMENT_QUESTION (ASSESSMENT_QUESTION_ID)
);

CREATE TABLE ASSESSMENT_STUDENT_ANSWER
(
    ASSESSMENT_STUDENT_ANSWER_ID               UUID                 NOT NULL,
    ASSESSMENT_QUESTION_RESPONSE_OPTION_ID     UUID                 NOT NULL,
    ASSESSMENT_STUDENT_ID                      UUID                 NOT NULL,
    CREATE_USER                                VARCHAR(100)         NOT NULL,
    CREATE_DATE                 TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER                                 VARCHAR(100)        NOT NULL,
    UPDATE_DATE                 TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ASSESSMENT_STUDENT_ANSWER_ID_PK PRIMARY KEY (ASSESSMENT_STUDENT_ANSWER_ID),
    CONSTRAINT FK_ASSESSMENT_QUESTION_RESPONSE_OPTION_ID FOREIGN KEY (ASSESSMENT_QUESTION_RESPONSE_OPTION_ID)
        REFERENCES ASSESSMENT_QUESTION_RESPONSE_OPTION (ASSESSMENT_QUESTION_RESPONSE_OPTION_ID),
    CONSTRAINT FK_ASSESSMENT_STUDENT_ID FOREIGN KEY (ASSESSMENT_STUDENT_ID)
        REFERENCES ASSESSMENT_STUDENT (ASSESSMENT_STUDENT_ID)
);

ALTER TABLE ASSESSMENT_STUDENT
    ADD COLUMN ASSESSMENT_FORM_ID              UUID,
    ADD COLUMN ADAPTED_ASSESSMENT_INDICATOR    VARCHAR(1),
    ADD COLUMN IRT_SCORE                       VARCHAR(7),
    ADD COLUMN SR_CHOICE_PATH                  VARCHAR(1),
    ADD CONSTRAINT FK_ASSESSMENT_FORM_ID FOREIGN KEY (ASSESSMENT_FORM_ID)
        REFERENCES ASSESSMENT_FORM (ASSESSMENT_FORM_ID);

INSERT INTO COGN_LEVEL_CODE (COGN_LEVEL_CODE, LABEL, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER, UPDATE_USER)
VALUES
    ('1', 'ORAL COMPONENT 1', 'ORAL COMPONENT 1', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('2', 'ORAL COMPONENT 2', 'ORAL COMPONENT 2', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('3', 'ORAL COMPONENT 3', 'ORAL COMPONENT 3', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('7', 'LEVEL 1 RECALL', 'LEVEL 1 RECALL', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('8', 'LEVEL 2 SKILL/CONCEPT', 'LEVEL 2 SKILL/CONCEPT', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('9', 'LEVEL 3 STRATEGIC THINKING', 'LEVEL 3 STRATEGIC THINKING', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('A', 'AUDITORY', 'AUDITORY', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('C', 'COMPOSITION', 'COMPOSITION', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('F', 'FRENCH AUDIO VIDEO', 'FRENCH AUDIO VIDEO', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('G', 'GRAMMAR', 'GRAMMAR', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('H', 'HIGHER MENTAL PROCESSES', 'HIGHER MENTAL PROCESSES', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('K', 'KNOWLEDGE', 'KNOWLEDGE', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('L', 'LISTENING', 'LISTENING', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('N', 'KNOWING', 'KNOWING', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('O', 'ORAL PROFICIENCY', 'ORAL PROFICIENCY', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('P', 'APPLYING', 'APPLYING', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('Q', 'REASONING', 'REASONING', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('R', 'RETRIEVE INFO/RECOGNIZE MEANING', 'RETRIEVE INFO/RECOGNIZE MEANING', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('S', 'SPEAKING', 'SPEAKING', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('U', 'UNDERSTANDING', 'UNDERSTANDING', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('W', 'RETRIEVE INFORMATION', 'RETRIEVE INFORMATION', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('X', 'RECOGNIZE MEANING', 'RECOGNIZE MEANING', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('Y', 'INTERPRET TEXTS', 'INTERPRET TEXTS', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('Z', 'ANALYZE TEXTS', 'ANALYZE TEXTS', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API');

INSERT INTO TASK_CODE (TASK_CODE, LABEL, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER, UPDATE_USER)
VALUES
    ('A', 'Part A', 'Part A', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('E', 'Part B - Literacy for Expression', 'Part B - Literacy for Expression', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('F', 'Fair Share', 'Fair Share', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('I', 'Part B - Literacy for Information', 'Part B - Literacy for Information', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('M', 'Model', 'Model', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('O', 'Oral', 'Oral', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('P', 'Plan and Design', 'Plan and Design', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('R', 'Reasoned Estimates', 'Reasoned Estimates', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API');

INSERT INTO CLAIM_CODE (CLAIM_CODE, LABEL, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER, UPDATE_USER)
VALUES
    ('A', 'ALL', 'ALL', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('C', 'Comprehend (Literacy Only)', 'Comprehend (Literacy Only)', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('I', 'Interpret', 'Interpret', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('N', 'Analyze', 'Analyze', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('O', 'Oral Communication', 'Oral Communication', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('P', 'Apply', 'Apply', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('S', 'Solve', 'Solve', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('W', 'Written Communication', 'Written Communication', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API');

INSERT INTO CONTEXT_CODE (CONTEXT_CODE, LABEL, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER, UPDATE_USER)
VALUES
    ('1', 'Career/Personal', 'Career/Personal', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('2', 'Personal/Societal', 'Personal/Societal', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('3', 'Career/Scientific', 'Career/Scientific', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('4', 'Career/Societal', 'Career/Societal', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('5', 'Personal/Scientific', 'Personal/Scientific', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('6', 'Scientific/Societal', 'Scientific/Societal', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('A', 'Career', 'Career', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('B', 'Personal', 'Personal', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('C', 'Scientific', 'Scientific', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('D', 'Societal', 'Societal', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API');

INSERT INTO CONCEPT_CODE (CONCEPT_CODE, LABEL, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER, UPDATE_USER)
VALUES
    ('D', 'Data and Probability', 'Data and Probability', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('DF', 'Data and Probability/Financial Literacy', 'Data and Probability/Financial Literacy', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('DFG', 'Data, Prob/Fin Lit/Geometry, Meas', 'Data, Prob/Fin Lit/Geometry, Meas', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('DFN', 'Data, Prob/Fin Lit/Number Sense', 'Data, Prob/Fin Lit/Number Sense', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('DFP', 'Data, Prob/Fin Lit/Patterns', 'Data, Prob/Fin Lit/Patterns', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('DG', 'Data, Probability/Geometry, Measurement', 'Data, Probability/Geometry, Measurement', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('DGN', 'Data, Prob/Geometry, Meas/Number Sense', 'Data, Prob/Geometry, Meas/Number Sense', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('DGP', 'Data, Prob/Geometry, Meas/Patterns', 'Data, Prob/Geometry, Meas/Patterns', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('DN', 'Data, Probability/Number Sense', 'Data, Probability/Number Sense', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('DNP', 'Data, Prob/Number Sense/Patterns', 'Data, Prob/Number Sense/Patterns', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('DP', 'Data and Probability/Patterns', 'Data and Probability/Patterns', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('F', 'Financial Literacy', 'Financial Literacy', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('FG', 'Financial Literacy/Geometry, Measurement', 'Financial Literacy/Geometry, Measurement', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('FGN', 'Fin Lit/Geometry, Meas/Number Sense', 'Fin Lit/Geometry, Meas/Number Sense', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('FGP', 'Fin Lit/Geometry, Meas/Patterns', 'Fin Lit/Geometry, Meas/Patterns', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('FN', 'Financial Literacy/Number Sense', 'Financial Literacy/Number Sense', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('FNP', 'Fin Lit/Number Sense/Patterns', 'Fin Lit/Number Sense/Patterns', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('FP', 'Financial Literacy/Patterns', 'Financial Literacy/Patterns', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('G', 'Geometry and Measurement', 'Geometry and Measurement', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('GN', 'Geometry and Measurement/Number Sense', 'Geometry and Measurement/Number Sense', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('GNP', 'Geometry, Meas/Number Sense/Patterns', 'Geometry, Meas/Number Sense/Patterns', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('GO', 'Graphic organizer', 'Graphic organizer', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('GP', 'Geometry and Measurement/Patterns', 'Geometry and Measurement/Patterns', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('N', 'Number Sense', 'Number Sense', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('NP', 'Number Sense/Patterns', 'Number Sense/Patterns', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('O1', 'Oral Component Partie 1', 'Oral Component Partie 1', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('O1D', 'Oral Component Partie 1, fond', 'Oral Component Partie 1, fond', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('O1E', 'Oral Component Partie 1, expression', 'Oral Component Partie 1, expression', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('O1F', 'Oral Component Partie 1, forme', 'Oral Component Partie 1, forme', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('O2', 'Oral Component Partie 2', 'Oral Component Partie 2', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('O2D', 'Oral Component Partie 2, fond', 'Oral Component Partie 2, fond', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('O2E', 'Oral Component Partie 2, expression', 'Oral Component Partie 2, expression', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('O2F', 'Oral Component Partie 2, forme', 'Oral Component Partie 2, forme', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('O3', 'Oral Component Partie 3', 'Oral Component Partie 3', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('P', 'Patterns', 'Patterns', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('WRA', 'Written Response - Long - Part A', 'Written Response - Long - Part A', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('WRB', 'Written', 'Written', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('WRD', 'Long Written Response, fond', 'Long Written Response, fond', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('WRF', 'Long Written Response, forme', 'Long Written Response, forme', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API'),
    ('WRS', 'Written response - Short', 'Written response - Short', TO_DATE('20250603', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 'ASSESSMENT-API', 'ASSESSMENT-API');