CREATE TABLE COMPONENT_TYPE_CODE
(
    COMPONENT_TYPE_CODE VARCHAR(10)                         NOT NULL,
    LABEL              VARCHAR(255)                        NOT NULL,
    DESCRIPTION        VARCHAR(255)                        NOT NULL,
    DISPLAY_ORDER      INTEGER   DEFAULT 10                NOT NULL,
    EFFECTIVE_DATE     TIMESTAMP                           NOT NULL,
    EXPIRY_DATE        TIMESTAMP                           NOT NULL,
    CREATE_USER        VARCHAR(100)                        NOT NULL,
    CREATE_DATE        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER        VARCHAR(100)                        NOT NULL,
    UPDATE_DATE        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT COMPONENT_TYPE_CODE_PK PRIMARY KEY (COMPONENT_TYPE_CODE)
);

ALTER TABLE ASSESSMENT_COMPONENT ADD CONSTRAINT ASSESSMENT_COMPONENT_TYPE_FK FOREIGN KEY (COMPONENT_TYPE_CODE) REFERENCES COMPONENT_TYPE_CODE (COMPONENT_TYPE_CODE);
ALTER TABLE ASSESSMENT_STUDENT_COMPONENT ADD CONSTRAINT ASSESSMENT_STUDENT_COMPONENT_TYPE_FK FOREIGN KEY (COMPONENT_TYPE_CODE) REFERENCES COMPONENT_TYPE_CODE (COMPONENT_TYPE_CODE);

INSERT INTO COMPONENT_TYPE_CODE (COMPONENT_TYPE_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE)
VALUES ('NONE','None','None',10,
        to_date('2019-07-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2099-12-31 00:00:00','YYYY-MM-DD HH24:MI:SS'),
        'ASSESSMENT-API', CURRENT_TIMESTAMP,'ASSESSMENT-API',CURRENT_TIMESTAMP);

INSERT INTO COMPONENT_TYPE_CODE (COMPONENT_TYPE_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE)
VALUES ('ORAL','Oral question','Oral question',10,
        to_date('2019-07-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2099-12-31 00:00:00','YYYY-MM-DD HH24:MI:SS')
           ,'ASSESSMENT-API', CURRENT_TIMESTAMP,'ASSESSMENT-API',CURRENT_TIMESTAMP);

CREATE TABLE COMPONENT_SUB_TYPE_CODE
(
    COMPONENT_SUB_TYPE_CODE VARCHAR(10)                         NOT NULL,
    LABEL              VARCHAR(255)                        NOT NULL,
    DESCRIPTION        VARCHAR(255)                        NOT NULL,
    DISPLAY_ORDER      INTEGER   DEFAULT 10                NOT NULL,
    EFFECTIVE_DATE     TIMESTAMP                           NOT NULL,
    EXPIRY_DATE        TIMESTAMP                           NOT NULL,
    CREATE_USER        VARCHAR(100)                        NOT NULL,
    CREATE_DATE        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER        VARCHAR(100)                        NOT NULL,
    UPDATE_DATE        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT COMPONENT_SUB_TYPE_CODE_PK PRIMARY KEY (COMPONENT_SUB_TYPE_CODE)
);

ALTER TABLE ASSESSMENT_COMPONENT ADD CONSTRAINT ASSESSMENT_COMPONENT_SUB_TYPE_FK FOREIGN KEY (COMPONENT_SUB_TYPE_CODE) REFERENCES COMPONENT_SUB_TYPE_CODE (COMPONENT_SUB_TYPE_CODE);
ALTER TABLE ASSESSMENT_STUDENT_COMPONENT ADD CONSTRAINT ASSESSMENT_STUDENT_COMPONENT_SUB_TYPE_FK FOREIGN KEY (COMPONENT_SUB_TYPE_CODE) REFERENCES COMPONENT_SUB_TYPE_CODE (COMPONENT_SUB_TYPE_CODE);

INSERT INTO COMPONENT_SUB_TYPE_CODE (COMPONENT_SUB_TYPE_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE)
VALUES ('M','Multiple Choice','Multiple Choice or Selected Choice',10,
        to_date('2019-07-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2099-12-31 00:00:00','YYYY-MM-DD HH24:MI:SS'),
        'ASSESSMENT-API', CURRENT_TIMESTAMP,'ASSESSMENT-API',CURRENT_TIMESTAMP);

INSERT INTO COMPONENT_SUB_TYPE_CODE (COMPONENT_SUB_TYPE_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE)
VALUES ('O','Open Ended','Open Ended',10,
        to_date('2019-07-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2099-12-31 00:00:00','YYYY-MM-DD HH24:MI:SS')
           ,'ASSESSMENT-API', CURRENT_TIMESTAMP,'ASSESSMENT-API',CURRENT_TIMESTAMP);