ALTER TABLE ASSESSMENT_QUESTION
    ADD COLUMN QUESTION_TYPE_CODE VARCHAR(10);

ALTER TABLE ASSESSMENT_QUESTION RENAME COLUMN CONCEPT_CODE TO CONCEPTS_CODE;

ALTER TABLE ASSESSMENT_QUESTION
DROP
COLUMN ITEM_TYPE;

CREATE TABLE QUESTION_TYPE_CODE
(
    QUESTION_TYPE_CODE VARCHAR(10)                         NOT NULL,
    LABEL              VARCHAR(255)                        NOT NULL,
    DESCRIPTION        VARCHAR(255)                        NOT NULL,
    DISPLAY_ORDER      INTEGER   DEFAULT 10                NOT NULL,
    EFFECTIVE_DATE     TIMESTAMP                           NOT NULL,
    EXPIRY_DATE        TIMESTAMP                           NOT NULL,
    CREATE_USER        VARCHAR(100)                        NOT NULL,
    CREATE_DATE        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER        VARCHAR(100)                        NOT NULL,
    UPDATE_DATE        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT QUESTION_TYPE_CODE_PK PRIMARY KEY (QUESTION_TYPE_CODE)
);

ALTER TABLE ASSESSMENT_QUESTION ADD CONSTRAINT ASSESSMENT_QUES_TYPE_FK FOREIGN KEY (QUESTION_TYPE_CODE) REFERENCES QUESTION_TYPE_CODE (QUESTION_TYPE_CODE);

INSERT INTO QUESTION_TYPE_CODE (QUESTION_TYPE_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE)
VALUES ('WRITTEN','Written question','Written question',10,
        to_date('2019-07-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2099-12-31 00:00:00','YYYY-MM-DD HH24:MI:SS'),
        'ASSESSMENT-API', CURRENT_TIMESTAMP,'ASSESSMENT-API',CURRENT_TIMESTAMP);

INSERT INTO QUESTION_TYPE_CODE (QUESTION_TYPE_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE)
VALUES ('ORAL','Oral question','Oral question',10,
        to_date('2019-07-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2099-12-31 00:00:00','YYYY-MM-DD HH24:MI:SS')
        ,'ASSESSMENT-API', CURRENT_TIMESTAMP,'ASSESSMENT-API',CURRENT_TIMESTAMP);