ALTER TABLE ASSESSMENT_SESSION
    ADD COLUMN APPROVAL_STUDENT_CERT_USER_ID VARCHAR(25);

ALTER TABLE ASSESSMENT_SESSION
    ADD COLUMN APPROVAL_STUDENT_CERT_SIGN_DATE TIMESTAMP;

ALTER TABLE ASSESSMENT_SESSION
    ADD COLUMN APPROVAL_ASSESSMENT_DESIGN_USER_ID VARCHAR(25);

ALTER TABLE ASSESSMENT_SESSION
    ADD COLUMN APPROVAL_ASSESSMENT_DESIGN_SIGN_DATE TIMESTAMP;

ALTER TABLE ASSESSMENT_SESSION
    ADD COLUMN APPROVAL_ASSESSMENT_ANALYSIS_USER_ID VARCHAR(25);

ALTER TABLE ASSESSMENT_SESSION
    ADD COLUMN APPROVAL_ASSESSMENT_ANALYSIS_SIGN_DATE TIMESTAMP;