ALTER TABLE ASSESSMENT_STUDENT_ANSWER DROP CONSTRAINT  FK_ASSESSMENT_QUESTION_RESPONSE_OPTION_ID;

DROP TABLE ASSESSMENT_QUESTION_RESPONSE_OPTION;

ALTER TABLE ASSESSMENT_STUDENT_ANSWER
    DROP COLUMN ASSESSMENT_QUESTION_RESPONSE_OPTION_ID;

ALTER TABLE ASSESSMENT_STUDENT_ANSWER
    ADD COLUMN ASSESSMENT_QUESTION_ID UUID NOT NULL,
    ADD COLUMN MC_ASSESSMENT_RESPONSE VARCHAR(75),
    ADD COLUMN MC_SCORE NUMERIC(5,1),
    ADD COLUMN NUM_OMITS NUMERIC,
    ADD COLUMN COMPONENT_TOTAL NUMERIC(5,1),
    ADD COLUMN COMPONENT_TOTAL VARCHAR(1),
    ADD COLUMN SR_CHOICE_PATH VARCHAR(1);

ALTER TABLE ASSESSMENT_STUDENT_ANSWER
    ADD CONSTRAINT FK_ASSESSMENT_QUESTION_ID FOREIGN KEY (ASSESSMENT_QUESTION_ID)
        REFERENCES ASSESSMENT_QUESTION (ASSESSMENT_QUESTION_ID);

ALTER TABLE ASSESSMENT_STUDENT
    DROP COLUMN SR_CHOICE_PATH;

ALTER TABLE ASSESSMENT_STUDENT
    ADD COLUMN RAW_SCORE NUMERIC(5,1),
    ADD COLUMN PRINT_CODE VARCHAR(1),
    ADD COLUMN PRE_PRINT_FLAG VARCHAR(1),
    ADD COLUMN MC_TOTAL NUMERIC(5,1),
    ADD COLUMN OE_TOTAL NUMERIC(5,1);
