ALTER TABLE ASSESSMENT_STUDENT
RENAME COLUMN SCHOOL_ID to SCHOOL_OF_RECORD_AT_WRITE_SCHOOL_ID;

ALTER TABLE ASSESSMENT_STUDENT
RENAME COLUMN ASSESSMENT_CENTER_ID to ASSESSMENT_CENTER_SCHOOL_ID;

ALTER TABLE ASSESSMENT_STUDENT
RENAME COLUMN IS_ELECTRONIC_EXAM TO IS_ELECTRONIC_ASSESSMENT;

ALTER TABLE ASSESSMENT_STUDENT
RENAME COLUMN LOCAL_COURSE_ID to LOCAL_ASSESSMENT_ID;

ALTER TABLE ASSESSMENT_STUDENT
DROP COLUMN PRE_PRINT_FLAG;

ALTER TABLE ASSESSMENT_STUDENT
DROP COLUMN PRINT_CODE;

ALTER TABLE ASSESSMENT_STUDENT
DROP COLUMN COURSE_STATUS_CODE;

ALTER TABLE ASSESSMENT_STUDENT
ADD COLUMN SCHOOL_OF_RECORD_ID UUID NOT NULL;

