ALTER TABLE ASSESSMENT_STUDENT
DROP COLUMN DISTRICT_ID;

DROP TABLE ASSESSMENT_STUDENT_HISTORY;

CREATE TABLE ASSESSMENT_STUDENT_HISTORY
(
    ASSESSMENT_STUDENT_HISTORY_ID       UUID                                NOT NULL,
    ASSESSMENT_STUDENT_ID               UUID                                NOT NULL,
    SCHOOL_OF_RECORD_AT_WRITE_SCHOOL_ID UUID                                NOT NULL,
    STUDENT_ID                          UUID                                NOT NULL,
    PEN                                 VARCHAR(9)                          NOT NULL,
    LOCAL_ID                            VARCHAR(12) NULL,
    IS_ELECTRONIC_ASSESSMENT            BOOL NULL,
    PROVINCIAL_SPECIAL_CASE_CODE        VARCHAR(1) NULL,
    CREATE_USER                         VARCHAR(100)                        NOT NULL,
    CREATE_DATE                         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER                         VARCHAR(100)                        NOT NULL,
    UPDATE_DATE                         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ASSESSMENT_ID                       UUID                                NOT NULL,
    ASSESSMENT_STUDENT_STATUS_CODE      VARCHAR(20)                         NOT NULL,
    PROFICIENCY_SCORE                   NUMERIC(1) NULL,
    SURNAME                             VARCHAR(25)                         NOT NULL,
    ASSESSMENT_CENTER_SCHOOL_ID         UUID NULL,
    GIVEN_NAME                          VARCHAR(25) NULL,
    NUMBER_OF_ATTEMPTS                  NUMERIC(1) NULL,
    LOCAL_ASSESSMENT_ID                 VARCHAR(20) NULL,
    ASSESSMENT_FORM_ID                  UUID NULL,
    ADAPTED_ASSESSMENT_INDICATOR        VARCHAR(1) NULL,
    IRT_SCORE                           VARCHAR(7) NULL,
    RAW_SCORE                           NUMERIC(5, 1) NULL,
    MC_TOTAL                            NUMERIC(5, 1) NULL,
    OE_TOTAL                            NUMERIC(5, 1) NULL,
    MARKING_SESSION                     VARCHAR(6) NULL,
    PERCENT_COMPLETE                    NUMERIC NULL,
    SCHOOL_OF_RECORD_ID                 UUID                                NOT NULL,
    CONSTRAINT ASSESSMENT_STUDENT_HISTORY_ID_PK PRIMARY KEY (ASSESSMENT_STUDENT_HISTORY_ID),
    CONSTRAINT ASSESSMENT_ID_FK FOREIGN KEY (ASSESSMENT_ID) REFERENCES ASSESSMENT (ASSESSMENT_ID),
    CONSTRAINT FK_ASSESSMENT_FORM_ID FOREIGN KEY (ASSESSMENT_FORM_ID) REFERENCES ASSESSMENT_FORM (ASSESSMENT_FORM_ID),
    CONSTRAINT FK_ASSESSMENT_ID FOREIGN KEY (ASSESSMENT_ID) REFERENCES ASSESSMENT (ASSESSMENT_ID),
    CONSTRAINT FK_ASSESSMENT_STUDENT_STATUS_CODE FOREIGN KEY (ASSESSMENT_STUDENT_STATUS_CODE) REFERENCES ASSESSMENT_STUDENT_STATUS_CODE (ASSESSMENT_STUDENT_STATUS_CODE),
    CONSTRAINT FK_PROVINCIAL_SPECIAL_CASE_CODE FOREIGN KEY (PROVINCIAL_SPECIAL_CASE_CODE) REFERENCES PROVINCIAL_SPECIAL_CASE_CODE (PROVINCIAL_SPECIAL_CASE_CODE)
);