ALTER TABLE ASSESSMENT_STUDENT
    RENAME COLUMN ADAPTED_ASSESSMENT_INDICATOR to ADAPTED_ASSESSMENT_CODE;

ALTER TABLE ASSESSMENT_STUDENT_HISTORY
    RENAME COLUMN ADAPTED_ASSESSMENT_INDICATOR to ADAPTED_ASSESSMENT_CODE;

CREATE TABLE ADAPTED_ASSESSMENT_CODE
(
    ADAPTED_ASSESSMENT_CODE VARCHAR(10)                         NOT NULL,
    LABEL              VARCHAR(255)                        NOT NULL,
    DESCRIPTION        VARCHAR(255)                        NOT NULL,
    DISPLAY_ORDER      INTEGER   DEFAULT 10                NOT NULL,
    EFFECTIVE_DATE     TIMESTAMP                           NOT NULL,
    EXPIRY_DATE        TIMESTAMP                           NOT NULL,
    CREATE_USER        VARCHAR(100)                        NOT NULL,
    CREATE_DATE        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER        VARCHAR(100)                        NOT NULL,
    UPDATE_DATE        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ADAPTED_ASSESSMENT_CODE_PK PRIMARY KEY (ADAPTED_ASSESSMENT_CODE)
);

ALTER TABLE ASSESSMENT_STUDENT ADD CONSTRAINT ADAPTED_ASSESSMENT_CODE_FK FOREIGN KEY (ADAPTED_ASSESSMENT_CODE) REFERENCES ADAPTED_ASSESSMENT_CODE (ADAPTED_ASSESSMENT_CODE);
ALTER TABLE ASSESSMENT_STUDENT_HISTORY ADD CONSTRAINT ADAPTED_ASSESSMENT_CODE_HIST_FK FOREIGN KEY (ADAPTED_ASSESSMENT_CODE) REFERENCES ADAPTED_ASSESSMENT_CODE (ADAPTED_ASSESSMENT_CODE);

INSERT INTO ADAPTED_ASSESSMENT_CODE (ADAPTED_ASSESSMENT_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE)
VALUES ('BRAILLE','Braille','Braille',10,
        to_date('2019-07-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2099-12-31 00:00:00','YYYY-MM-DD HH24:MI:SS'),
        'ASSESSMENT-API', CURRENT_TIMESTAMP,'ASSESSMENT-API',CURRENT_TIMESTAMP);

INSERT INTO ADAPTED_ASSESSMENT_CODE (ADAPTED_ASSESSMENT_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE)
VALUES ('LARGEPRINT','Large Print','Large Print',10,
        to_date('2019-07-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2099-12-31 00:00:00','YYYY-MM-DD HH24:MI:SS')
           ,'ASSESSMENT-API', CURRENT_TIMESTAMP,'ASSESSMENT-API',CURRENT_TIMESTAMP);