ALTER TABLE ADAPTED_ASSESSMENT_CODE
ADD COLUMN LEGACY_CODE VARCHAR(1);

UPDATE ADAPTED_ASSESSMENT_CODE
SET LEGACY_CODE = 'L'
WHERE ADAPTED_ASSESSMENT_CODE = 'LARGEPRINT';

UPDATE ADAPTED_ASSESSMENT_CODE
SET LEGACY_CODE = 'B'
WHERE ADAPTED_ASSESSMENT_CODE = 'BRAILLE';
