ALTER TABLE ASSESSMENT_STUDENT DROP CONSTRAINT ASSESSMENT_ID_FK;

CREATE INDEX ASSESSMENT_STUDENT_PROFICIENCY_SCORE_IDX ON ASSESSMENT_STUDENT (PROFICIENCY_SCORE);
CREATE INDEX ASSESSMENT_STUDENT_PROVINCIAL_SPECIAL_CASE_IDX ON ASSESSMENT_STUDENT (PROVINCIAL_SPECIAL_CASE_CODE);
CREATE INDEX ASSESSMENT_TYPE_CODE_IDX ON ASSESSMENT (ASSESSMENT_TYPE_CODE);
CREATE INDEX ASSESSMENT_SESSION_ID_IDX ON ASSESSMENT (SESSION_ID);