ALTER TABLE ASSESSMENT_STUDENT_COMPONENT
    ADD COLUMN ASSESSMENT_FORM_ID UUID NOT NULL;

ALTER TABLE ASSESSMENT_STUDENT_COMPONENT
    DROP COLUMN COMPONENT_TYPE_CODE;

ALTER TABLE ASSESSMENT_STUDENT_COMPONENT
    DROP COLUMN COMPONENT_SUB_TYPE_CODE;

ALTER TABLE ASSESSMENT_STUDENT_COMPONENT
    ADD CONSTRAINT FK_ASSESSMENT_STUDENT_COMPONENT_FORM_ID FOREIGN KEY (ASSESSMENT_FORM_ID)
        REFERENCES ASSESSMENT_FORM (ASSESSMENT_FORM_ID);

ALTER TABLE ASSESSMENT_STUDENT_ANSWER
    ADD COLUMN ASSESSMENT_QUESTION_ID UUID NOT NULL;

ALTER TABLE ASSESSMENT_STUDENT_ANSWER
DROP COLUMN ITEM_NUMBER;

ALTER TABLE ASSESSMENT_STUDENT_ANSWER
DROP COLUMN QUESTION_NUMBER;

ALTER TABLE ASSESSMENT_STUDENT_ANSWER
    ADD CONSTRAINT FK_ASSESSMENT_STUDENT_ANSWER_COMPONENT_ID FOREIGN KEY (ASSESSMENT_STUDENT_COMPONENT_ID)
        REFERENCES ASSESSMENT_STUDENT_COMPONENT (ASSESSMENT_STUDENT_COMPONENT_ID);

ALTER TABLE ASSESSMENT_STUDENT_ANSWER
    ADD CONSTRAINT FK_ASSESSMENT_STUDENT_ANSWER_QUESTION_ID FOREIGN KEY (ASSESSMENT_QUESTION_ID)
        REFERENCES ASSESSMENT_QUESTION (ASSESSMENT_QUESTION_ID);

ALTER TABLE ASSESSMENT_STUDENT
DROP COLUMN IS_ELECTRONIC_ASSESSMENT;

ALTER TABLE ASSESSMENT_STUDENT_HISTORY
DROP COLUMN IS_ELECTRONIC_ASSESSMENT;

ALTER TABLE ASSESSMENT_STUDENT
DROP COLUMN RAW_SCORE;

ALTER TABLE ASSESSMENT_STUDENT_HISTORY
DROP COLUMN RAW_SCORE;

ALTER TABLE ASSESSMENT_STUDENT
DROP COLUMN MC_TOTAL;

ALTER TABLE ASSESSMENT_STUDENT_HISTORY
DROP COLUMN MC_TOTAL;

ALTER TABLE ASSESSMENT_STUDENT
DROP COLUMN OE_TOTAL;

ALTER TABLE ASSESSMENT_STUDENT_HISTORY
DROP COLUMN OE_TOTAL;

ALTER TABLE ASSESSMENT_STUDENT_COMPONENT
DROP COLUMN COMPONENT_TOTAL;

ALTER TABLE ASSESSMENT_STUDENT_COMPONENT
DROP COLUMN COMPONENT_SOURCE;

ALTER TABLE ASSESSMENT_STUDENT_ANSWER
DROP COLUMN MC_ASSESSMENT_RESPONSE_UNSORTED;

ALTER TABLE ASSESSMENT_STUDENT_ANSWER
DROP COLUMN MC_ASSESSMENT_RESPONSE_SORTED;