ALTER TABLE ASSESSMENT_STUDENT_COMPONENT
    ADD COLUMN ASSESSMENT_FORM_ID UUID NOT NULL;

ALTER TABLE ASSESSMENT_STUDENT_COMPONENT
DROP
COLUMN COMPONENT_TYPE_CODE;

ALTER TABLE ASSESSMENT_STUDENT_COMPONENT
DROP
COLUMN COMPONENT_SUB_TYPE_CODE;

ALTER TABLE ASSESSMENT_STUDENT_COMPONENT
    ADD CONSTRAINT FK_ASSESSMENT_STUDENT_COMPONENT_FORM_ID FOREIGN KEY (ASSESSMENT_FORM_ID)
        REFERENCES ASSESSMENT_FORM (ASSESSMENT_FORM_ID);

ALTER TABLE ASSESSMENT_STUDENT_ANSWER
    ADD COLUMN ASSESSMENT_QUESTION_ID UUID NOT NULL;

ALTER TABLE ASSESSMENT_STUDENT_ANSWER
DROP
COLUMN ITEM_NUMBER;

ALTER TABLE ASSESSMENT_STUDENT_ANSWER
DROP
COLUMN QUESTION_NUMBER;

ALTER TABLE ASSESSMENT_STUDENT_ANSWER
    ADD CONSTRAINT FK_ASSESSMENT_STUDENT_ANSWER_COMPONENT_ID FOREIGN KEY (ASSESSMENT_STUDENT_COMPONENT_ID)
        REFERENCES ASSESSMENT_STUDENT_COMPONENT (ASSESSMENT_STUDENT_COMPONENT_ID);

ALTER TABLE ASSESSMENT_STUDENT_ANSWER
    ADD CONSTRAINT FK_ASSESSMENT_STUDENT_ANSWER_QUESTION_ID FOREIGN KEY (ASSESSMENT_QUESTION_ID)
        REFERENCES ASSESSMENT_QUESTION (ASSESSMENT_QUESTION_ID);

ALTER TABLE ASSESSMENT_STUDENT
DROP
COLUMN IS_ELECTRONIC_ASSESSMENT;

ALTER TABLE ASSESSMENT_STUDENT_HISTORY
DROP
COLUMN IS_ELECTRONIC_ASSESSMENT;

ALTER TABLE ASSESSMENT_STUDENT
DROP
COLUMN PERCENT_COMPLETE;

ALTER TABLE ASSESSMENT_STUDENT_HISTORY
DROP
COLUMN PERCENT_COMPLETE;

ALTER TABLE ASSESSMENT_STUDENT_COMPONENT
DROP
COLUMN COMPONENT_TOTAL;

ALTER TABLE ASSESSMENT_STUDENT_COMPONENT
DROP
COLUMN COMPONENT_SOURCE;

ALTER TABLE ASSESSMENT_STUDENT_ANSWER
DROP
COLUMN MC_ASSESSMENT_RESPONSE_UNSORTED;

ALTER TABLE ASSESSMENT_STUDENT_ANSWER
DROP
COLUMN MC_ASSESSMENT_RESPONSE_SORTED;

CREATE TABLE STAGED_ASSESSMENT_STUDENT
(
    ASSESSMENT_STUDENT_ID               UUID                                NOT NULL,
    SCHOOL_OF_RECORD_AT_WRITE_SCHOOL_ID UUID NULL,
    STUDENT_ID                          UUID                                NOT NULL,
    ASSESSMENT_ID                       UUID                                NOT NULL,
    ASSESSMENT_FORM_ID                  UUID NULL,
    PEN                                 VARCHAR(9)                          NOT NULL,
    LOCAL_ID                            VARCHAR(12) NULL,
    PROVINCIAL_SPECIAL_CASE_CODE        VARCHAR(1) NULL,
    PROFICIENCY_SCORE                   NUMERIC(1) NULL,
    SURNAME                             VARCHAR(25)                         NOT NULL,
    ASSESSMENT_CENTER_SCHOOL_ID         UUID NULL,
    GIVEN_NAME                          VARCHAR(25) NULL,
    NUMBER_OF_ATTEMPTS                  NUMERIC(1) NULL,
    LOCAL_ASSESSMENT_ID                 VARCHAR(20) NULL,
    ADAPTED_ASSESSMENT_CODE             VARCHAR(10) NULL,
    IRT_SCORE                           VARCHAR(7) NULL,
    RAW_SCORE                           NUMERIC(5, 1) NULL,
    MC_TOTAL                            NUMERIC(5, 1) NULL,
    OE_TOTAL                            NUMERIC(5, 1) NULL,
    MARKING_SESSION                     VARCHAR(6) NULL,
    SCHOOL_OF_RECORD_SCHOOL_ID          UUID                                NOT NULL,
    CREATE_USER                         VARCHAR(100)                        NOT NULL,
    CREATE_DATE                         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER                         VARCHAR(100)                        NOT NULL,
    UPDATE_DATE                         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT STAGED_ASSESSMENT_STUDENT_ID_PK PRIMARY KEY (ASSESSMENT_STUDENT_ID),
    CONSTRAINT STAGED_ADAPTED_ASSESSMENT_CODE_FK FOREIGN KEY (ADAPTED_ASSESSMENT_CODE) REFERENCES ADAPTED_ASSESSMENT_CODE (ADAPTED_ASSESSMENT_CODE),
    CONSTRAINT STAGED_ASSESSMENT_ID_FK FOREIGN KEY (ASSESSMENT_ID) REFERENCES ASSESSMENT (ASSESSMENT_ID),
    CONSTRAINT FK_STAGED_ASSESSMENT_FORM_ID FOREIGN KEY (ASSESSMENT_FORM_ID) REFERENCES ASSESSMENT_FORM (ASSESSMENT_FORM_ID),
    CONSTRAINT FK_STAGED_ASSESSMENT_ID FOREIGN KEY (ASSESSMENT_ID) REFERENCES ASSESSMENT (ASSESSMENT_ID),
    CONSTRAINT FK_STAGED_PROVINCIAL_SPECIAL_CASE_CODE FOREIGN KEY (PROVINCIAL_SPECIAL_CASE_CODE) REFERENCES PROVINCIAL_SPECIAL_CASE_CODE (PROVINCIAL_SPECIAL_CASE_CODE)
);

CREATE TABLE STAGED_ASSESSMENT_STUDENT_COMPONENT
(
    ASSESSMENT_STUDENT_COMPONENT_ID UUID                                NOT NULL,
    ASSESSMENT_STUDENT_ID           UUID                                NOT NULL,
    ASSESSMENT_COMPONENT_ID         UUID                                NOT NULL,
    CHOICE_PATH_ID                  VARCHAR(1) NULL,
    CREATE_USER                     VARCHAR(100)                        NOT NULL,
    CREATE_DATE                     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER                     VARCHAR(100)                        NOT NULL,
    UPDATE_DATE                     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT STAGED_ASSESSMENT_STUDENT_COMPONENT_ID_PK PRIMARY KEY (ASSESSMENT_STUDENT_COMPONENT_ID),
    CONSTRAINT STAGED_ASSESSMENT_STUDENT_COMPONENT_ID_FK FOREIGN KEY (ASSESSMENT_COMPONENT_ID) REFERENCES ASSESSMENT_COMPONENT (ASSESSMENT_COMPONENT_ID),
    CONSTRAINT FK_STAGED_ASSESSMENT_STUDENT_COMPONENT_ID FOREIGN KEY (ASSESSMENT_STUDENT_ID) REFERENCES STAGED_ASSESSMENT_STUDENT (ASSESSMENT_STUDENT_ID)
);

CREATE TABLE STAGED_ASSESSMENT_STUDENT_ANSWER
(
    ASSESSMENT_STUDENT_ANSWER_ID    UUID                                NOT NULL,
    ASSESSMENT_STUDENT_COMPONENT_ID UUID                                NOT NULL,
    ASSESSMENT_QUESTION_ID UUID                                NOT NULL,
    SCORE                           NUMERIC NULL,
    CREATE_USER                     VARCHAR(100)                        NOT NULL,
    CREATE_DATE                     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER                     VARCHAR(100)                        NOT NULL,
    UPDATE_DATE                     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT STAGED_ASSESSMENT_STUDENT_ANSWER_ID_PK PRIMARY KEY (ASSESSMENT_STUDENT_ANSWER_ID),
    CONSTRAINT STAGED_ASSESSMENT_STUDENT_ANSWER_QUESTION_ID_PK FOREIGN KEY (ASSESSMENT_QUESTION_ID) REFERENCES ASSESSMENT_QUESTION (ASSESSMENT_QUESTION_ID),
    CONSTRAINT FK_STAGED_ASSESSMENT_STUDENT_COMPONENT_ID FOREIGN KEY (ASSESSMENT_STUDENT_COMPONENT_ID) REFERENCES STAGED_ASSESSMENT_STUDENT_COMPONENT (ASSESSMENT_STUDENT_COMPONENT_ID)
);