ALTER TABLE STAGED_ASSESSMENT_STUDENT
    ADD COLUMN STAGED_ASSESSMENT_STUDENT_STATUS  VARCHAR(10) NOT NULL;

ALTER TABLE STAGED_ASSESSMENT_STUDENT ALTER COLUMN STUDENT_ID DROP NOT NULL;
ALTER TABLE STAGED_ASSESSMENT_STUDENT ALTER COLUMN SURNAME DROP NOT NULL;

CREATE INDEX STAGED_ASSESSMENT_STUDENT_STATUS_IDX ON STAGED_ASSESSMENT_STUDENT (STAGED_ASSESSMENT_STUDENT_STATUS);
CREATE INDEX STAGED_STUDENT_RESULT_STATUS_IDX ON STAGED_STUDENT_RESULT (STAGED_STUDENT_RESULT_STATUS);