ALTER TABLE ASSESSMENT_SESSION
    ADD COLUMN ASSESSMENT_REGISTRATIONS_EXPORT_USER_ID VARCHAR(25);

ALTER TABLE ASSESSMENT_SESSION
    ADD COLUMN ASSESSMENT_REGISTRATIONS_EXPORT_DATE TIMESTAMP;

ALTER TABLE ASSESSMENT_SESSION
    ADD COLUMN SESSION_WRITING_ATTEMPTS_EXPORT_USER_ID VARCHAR(25);

ALTER TABLE ASSESSMENT_SESSION
    ADD COLUMN SESSION_WRITING_ATTEMPTS_EXPORT_DATE TIMESTAMP;

ALTER TABLE ASSESSMENT_SESSION
    ADD COLUMN PEN_MERGES_EXPORT_USER_ID VARCHAR(25);

ALTER TABLE ASSESSMENT_SESSION
    ADD COLUMN PEN_MERGES_EXPORT_DATE TIMESTAMP;