CREATE TABLE ASSESSMENT_CHOICE
(
    ASSESSMENT_CHOICE_ID          UUID                                NOT NULL,
    ASSESSMENT_COMPONENT_ID     UUID                                NOT NULL,
    ITEM_NUMBER         NUMERIC                             NOT NULL,
    CREATE_USER                 VARCHAR(100)                        NOT NULL,
    CREATE_DATE                 TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER                 VARCHAR(100)                        NOT NULL,
    UPDATE_DATE                 TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ASSESSMENT_CHOICE_ID_PK PRIMARY KEY (ASSESSMENT_CHOICE_ID),
    CONSTRAINT FK_ASSESSMENT_COMPONENT_ID FOREIGN KEY (ASSESSMENT_COMPONENT_ID)
        REFERENCES ASSESSMENT_COMPONENT (ASSESSMENT_COMPONENT_ID)
);

CREATE TABLE ASSESSMENT_STUDENT_CHOICE
(
    ASSESSMENT_STUDENT_CHOICE_ID UUID                                NOT NULL,
    ASSESSMENT_STUDENT_COMPONENT_ID     UUID                                NOT NULL,
    ASSESSMENT_CHOICE_ID          UUID                                NOT NULL,
    CREATE_USER                         VARCHAR(100)                        NOT NULL,
    CREATE_DATE                         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER                         VARCHAR(100)                        NOT NULL,
    UPDATE_DATE                         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ASSESSMENT_STUDENT_CHOICE_ID_PK PRIMARY KEY (ASSESSMENT_STUDENT_CHOICE_ID),
    CONSTRAINT FK_ASSESSMENT_STUDENT_COMPONENT_ID FOREIGN KEY (ASSESSMENT_STUDENT_COMPONENT_ID)
        REFERENCES ASSESSMENT_STUDENT_COMPONENT (ASSESSMENT_STUDENT_COMPONENT_ID),
    CONSTRAINT FK_ASSESSMENT_CHOICE FOREIGN KEY (ASSESSMENT_CHOICE_ID)
        REFERENCES ASSESSMENT_CHOICE (ASSESSMENT_CHOICE_ID)
);

CREATE TABLE STAGED_ASSESSMENT_STUDENT_CHOICE
(
    ASSESSMENT_STUDENT_CHOICE_ID UUID                                NOT NULL,
    ASSESSMENT_STUDENT_COMPONENT_ID     UUID                                NOT NULL,
    ASSESSMENT_CHOICE_ID          UUID                                NOT NULL,
    CREATE_USER                         VARCHAR(100)                        NOT NULL,
    CREATE_DATE                         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER                         VARCHAR(100)                        NOT NULL,
    UPDATE_DATE                         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT STAGED_ASSESSMENT_STUDENT_CHOICE_PK PRIMARY KEY (ASSESSMENT_STUDENT_CHOICE_ID),
    CONSTRAINT FK_STAGED_ASSESSMENT_STUDENT_COMPONENT_ID FOREIGN KEY (ASSESSMENT_STUDENT_COMPONENT_ID)
        REFERENCES STAGED_ASSESSMENT_STUDENT_COMPONENT (ASSESSMENT_STUDENT_COMPONENT_ID),
    CONSTRAINT FK_ASSESSMENT_CHOICE FOREIGN KEY (ASSESSMENT_CHOICE_ID)
        REFERENCES ASSESSMENT_CHOICE (ASSESSMENT_CHOICE_ID)
);

ALTER TABLE ASSESSMENT_QUESTION ADD COLUMN ASSESSMENT_CHOICE_ID UUID;
ALTER TABLE ASSESSMENT_STUDENT_ANSWER ADD COLUMN ASSESSMENT_STUDENT_CHOICE_ID UUID;
ALTER TABLE STAGED_ASSESSMENT_STUDENT_ANSWER ADD COLUMN ASSESSMENT_STUDENT_CHOICE_ID UUID;

ALTER TABLE ASSESSMENT_QUESTION
    ADD CONSTRAINT FK_ASSESSMENT_CHOICE_ID FOREIGN KEY (ASSESSMENT_CHOICE_ID)
        REFERENCES ASSESSMENT_CHOICE (ASSESSMENT_CHOICE_ID) ON DELETE CASCADE;

ALTER TABLE ASSESSMENT_STUDENT_ANSWER
    ADD CONSTRAINT FK_ASSESSMENT_STUDENT_CHOICE_ID FOREIGN KEY (ASSESSMENT_STUDENT_CHOICE_ID)
        REFERENCES ASSESSMENT_STUDENT_CHOICE (ASSESSMENT_STUDENT_CHOICE_ID) ON DELETE CASCADE;

ALTER TABLE STAGED_ASSESSMENT_STUDENT_ANSWER
    ADD CONSTRAINT FK_STAGED_ASSESSMENT_STUDENT_CHOICE_ID FOREIGN KEY (ASSESSMENT_STUDENT_CHOICE_ID)
        REFERENCES STAGED_ASSESSMENT_STUDENT_CHOICE (ASSESSMENT_STUDENT_CHOICE_ID) ON DELETE CASCADE;