ALTER TABLE ASSESSMENT_STUDENT ADD COLUMN STUDENT_STATUS_CODE VARCHAR(10) DEFAULT 'ACTIVE';
ALTER TABLE ASSESSMENT_STUDENT DROP COLUMN STUDENT_STATUS;

CREATE TABLE STUDENT_STATUS_CODE
(
    STUDENT_STATUS_CODE  VARCHAR(10)                            NOT NULL,
    LABEL                VARCHAR(50)                            NOT NULL,
    DESCRIPTION          VARCHAR(255)                           NOT NULL,
    DISPLAY_ORDER        NUMERIC   DEFAULT 1                    NOT NULL,
    EFFECTIVE_DATE       TIMESTAMP                              NOT NULL,
    EXPIRY_DATE          TIMESTAMP                              NOT NULL,
    CREATE_USER          VARCHAR(32)                            NOT NULL,
    CREATE_DATE          TIMESTAMP DEFAULT CURRENT_TIMESTAMP    NOT NULL,
    UPDATE_USER          VARCHAR(32)                            NOT NULL,
    UPDATE_DATE          TIMESTAMP DEFAULT CURRENT_TIMESTAMP    NOT NULL,
    CONSTRAINT STUDENT_STATUS_CODE_PK PRIMARY KEY (STUDENT_STATUS_CODE)
);

INSERT INTO STUDENT_STATUS_CODE (STUDENT_STATUS_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE)
VALUES ('ACTIVE','Active','The assessment student is active.',10,
        to_date('2024-10-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2099-12-31 00:00:00','YYYY-MM-DD HH24:MI:SS'),
        'ASSESSMENT-API', CURRENT_TIMESTAMP,'ASSESSMENT-API',CURRENT_TIMESTAMP);

INSERT INTO STUDENT_STATUS_CODE (STUDENT_STATUS_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE)
VALUES ('MERGED','Merged','The upstream student id was merged with another student id.',10,
        to_date('2024-10-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2099-12-31 00:00:00','YYYY-MM-DD HH24:MI:SS'),
        'ASSESSMENT-API', CURRENT_TIMESTAMP,'ASSESSMENT-API',CURRENT_TIMESTAMP);

ALTER TABLE ASSESSMENT_STUDENT
    ADD CONSTRAINT FK_STUDENT_STATUS_CODE FOREIGN KEY (STUDENT_STATUS_CODE)
        REFERENCES STUDENT_STATUS_CODE (STUDENT_STATUS_CODE);
