ALTER TABLE ASSESSMENT_STUDENT
ALTER COLUMN RAW_SCORE TYPE NUMERIC(6,1);

ALTER TABLE ASSESSMENT_STUDENT_HISTORY
ALTER COLUMN RAW_SCORE TYPE NUMERIC(6,1);

ALTER TABLE STAGED_ASSESSMENT_STUDENT
ALTER COLUMN RAW_SCORE TYPE NUMERIC(6,1);

ALTER TABLE ASSESSMENT_STUDENT
ALTER COLUMN MC_TOTAL TYPE NUMERIC(6,1);

ALTER TABLE ASSESSMENT_STUDENT_HISTORY
ALTER COLUMN MC_TOTAL TYPE NUMERIC(6,1);

ALTER TABLE STAGED_ASSESSMENT_STUDENT
ALTER COLUMN MC_TOTAL TYPE NUMERIC(6,1);

ALTER TABLE ASSESSMENT_STUDENT
ALTER COLUMN OE_TOTAL TYPE NUMERIC(6,1);

ALTER TABLE ASSESSMENT_STUDENT_HISTORY
ALTER COLUMN OE_TOTAL TYPE NUMERIC(6,1);

ALTER TABLE STAGED_ASSESSMENT_STUDENT
ALTER COLUMN OE_TOTAL TYPE NUMERIC(6,1);