ALTER TABLE ASSESSMENT_SAGA
ADD COLUMN ASSESSMENT_ID  UUID;

ALTER TABLE ASSESSMENT_SAGA
ADD COLUMN PEN  VARCHAR(9);

CREATE INDEX ASSESSMENT_SAGA_ASSESSMENT_ID_PEN ON ASSESSMENT_SAGA (ASSESSMENT_ID, PEN);
CREATE INDEX STAGED_STUDENT_RESULT_UPLOAD_ASSESSMENT_ID_PEN ON STAGED_STUDENT_RESULT_UPLOAD (ASSESSMENT_ID, PEN);