ALTER TABLE ASSESSMENT_STUDENT_ANSWER
    DROP CONSTRAINT FK_ASSESSMENT_STUDENT_CHOICE_ID;

ALTER TABLE ASSESSMENT_STUDENT_ANSWER
    ADD CONSTRAINT FK_ASSESSMENT_STUDENT_CHOICE_ID FOREIGN KEY (ASSESSMENT_STUDENT_CHOICE_ID)
        REFERENCES ASSESSMENT_STUDENT_CHOICE (ASSESSMENT_STUDENT_CHOICE_ID);
