CREATE TABLE STAGED_ASSESSMENT_STUDENT_CHOICE_QUESTION_SET
(
    ASSESSMENT_STUDENT_CHOICE_QUESTION_SET_ID UUID                                NOT NULL,
    ASSESSMENT_STUDENT_CHOICE_ID     UUID                                NOT NULL,
    ASSESSMENT_QUESTION_ID           UUID                                NOT NULL,
    CREATE_USER                         VARCHAR(100)                        NOT NULL,
    CREATE_DATE                         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER                         VARCHAR(100)                        NOT NULL,
    UPDATE_DATE                         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT STAGED_ASSESSMENT_STUDENT_CHOICE_QUESTION_SET_ID_PK PRIMARY KEY (ASSESSMENT_STUDENT_CHOICE_QUESTION_SET_ID),
    CONSTRAINT FK_STAGED_ASSESSMENT_STUDENT_CHOICE_ID FOREIGN KEY (ASSESSMENT_STUDENT_CHOICE_ID)
        REFERENCES STAGED_ASSESSMENT_STUDENT_CHOICE (ASSESSMENT_STUDENT_CHOICE_ID) ON DELETE CASCADE,
    CONSTRAINT FK_STAGED_ASSESSMENT_QUESTION_ID FOREIGN KEY (ASSESSMENT_QUESTION_ID)
        REFERENCES ASSESSMENT_QUESTION (ASSESSMENT_QUESTION_ID)
);
CREATE INDEX STAGED_ASSESSMENT_STUDENT_CHOICE_QUESTION_SET_CHOICE_ID_IDX ON STAGED_ASSESSMENT_STUDENT_CHOICE_QUESTION_SET (ASSESSMENT_STUDENT_CHOICE_ID);
CREATE INDEX STAGED_ASSESSMENT_STUDENT_CHOICE_QUESTION_SET_QUESTION_ID_IDX ON STAGED_ASSESSMENT_STUDENT_CHOICE_QUESTION_SET (ASSESSMENT_QUESTION_ID);

CREATE TABLE ASSESSMENT_STUDENT_CHOICE_QUESTION_SET
(
    ASSESSMENT_STUDENT_CHOICE_QUESTION_SET_ID UUID                                NOT NULL,
    ASSESSMENT_STUDENT_CHOICE_ID     UUID                                NOT NULL,
    ASSESSMENT_QUESTION_ID           UUID                                NOT NULL,
    CREATE_USER                         VARCHAR(100)                        NOT NULL,
    CREATE_DATE                         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER                         VARCHAR(100)                        NOT NULL,
    UPDATE_DATE                         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ASSESSMENT_STUDENT_CHOICE_QUESTION_SET_ID_PK PRIMARY KEY (ASSESSMENT_STUDENT_CHOICE_QUESTION_SET_ID),
    CONSTRAINT FK_ASSESSMENT_STUDENT_CHOICE_ID FOREIGN KEY (ASSESSMENT_STUDENT_CHOICE_ID)
        REFERENCES ASSESSMENT_STUDENT_CHOICE (ASSESSMENT_STUDENT_CHOICE_ID),
    CONSTRAINT FK_ASSESSMENT_QUESTION_ID FOREIGN KEY (ASSESSMENT_QUESTION_ID)
        REFERENCES ASSESSMENT_QUESTION (ASSESSMENT_QUESTION_ID)
);
CREATE INDEX ASSESSMENT_STUDENT_CHOICE_QUESTION_SET_CHOICE_ID_IDX ON ASSESSMENT_STUDENT_CHOICE_QUESTION_SET (ASSESSMENT_STUDENT_CHOICE_ID);
CREATE INDEX ASSESSMENT_STUDENT_CHOICE_QUESTION_SET_QUESTION_ID_IDX ON ASSESSMENT_STUDENT_CHOICE_QUESTION_SET (ASSESSMENT_QUESTION_ID);

