ALTER TABLE ASSESSMENT_STUDENT_DOAR_CALCULATION DROP CONSTRAINT FK_ASSESSMENT_STUDENT_ID;

ALTER TABLE ASSESSMENT_STUDENT_DOAR_CALCULATION ADD CONSTRAINT FK_ASSESSMENT_STUDENT_ID
    FOREIGN KEY (ASSESSMENT_STUDENT_ID) REFERENCES ASSESSMENT_STUDENT (ASSESSMENT_STUDENT_ID) ON DELETE CASCADE;
