ALTER TABLE ASSESSMENT_STUDENT
    ADD CONSTRAINT UK_ASSESSMENT_STUDENT_STUDENT_ASSESSMENT
        UNIQUE (STUDENT_ID, ASSESSMENT_ID);

ALTER TABLE ASSESSMENT_SAGA
    ADD CONSTRAINT UK_SAGA_STAGED_ASSESSMENT_STUDENT
        UNIQUE (STAGED_ASSESSMENT_STUDENT_ID);

