package ca.bc.gov.educ.assessment.api.constants;

public enum EventType {
  INITIATED, //Default. Used by BaseOrchestrator.
  MARK_SAGA_COMPLETE, //Default. Used by BaseOrchestrator.
  GET_PAGINATED_SCHOOLS,
  GET_MERGES_IN_DATE_RANGE,
  PROCESS_STUDENT_REGISTRATION,
  GET_STUDENT_ASSESSMENT_DETAILS,
  PUBLISH_STUDENT_REGISTRATION_EVENT,
  PUBLISH_STUDENT_REGISTRATION,
  GET_OPEN_ASSESSMENT_SESSIONS,
  GET_STUDENT,
  GET_STUDENTS,
  ASSESSMENT_STUDENT_UPDATE,
  GENERATE_XAM_FILES
}
