package ca.bc.gov.educ.assessment.api.constants;

public enum EventType {
  INITIATED, //Default. Used by BaseOrchestrator.
  MARK_SAGA_COMPLETE, //Default. Used by BaseOrchestrator.
  GET_PAGINATED_SCHOOLS,
  GET_MERGES_IN_DATE_RANGE,
  PROCESS_STUDENT_REGISTRATION,
  GET_STUDENT_ASSESSMENT_DETAILS,
  PUBLISH_STUDENT_REGISTRATION_EVENT,
  PUBLISH_STUDENT_REGISTRATION,
  CREATE_MERGE,
  DELETE_MERGE,
  NOTIFY_GRAD_OF_UPDATED_STUDENTS,
  NOTIFY_MYED_OF_UPDATED_STUDENTS,
  GET_OPEN_ASSESSMENT_SESSIONS,
  GET_STUDENT,
  GET_STUDENTS,
  ASSESSMENT_STUDENT_UPDATE,
  UPDATE_SCHOOL_OF_RECORD,
  GET_GRAD_STUDENT_RECORD,
  GENERATE_XAM_FILES_AND_UPLOAD,
  READ_STUDENT_RESULT_FOR_PROCESSING,
  CREATE_STUDENT_RESULT,
  MARK_STAGED_STUDENTS_READY_FOR_TRANSFER,
  PROCESS_STUDENT_TRANSFER_EVENT,
  GET_ASSESSMENT_STUDENTS,
  CALCULATE_STUDENT_DOAR,
  GRAD_STUDENT_GRADUATED,
  GRAD_STUDENT_UNDO_COMPLETION,
  GRAD_STUDENT_UPDATED
}
