package ca.bc.gov.educ.assessment.api.constants;

/**
 * The enum Event outcome.
 */
public enum EventOutcome {
  INITIATE_SUCCESS,
  SESSIONS_FOUND,
  STUDENT_REGISTRATION_PROCESSED_IN_ASSESSMENT_API,
  STUDENT_REGISTRATION_EVENT_READ,
  STUDENT_REGISTRATION_PUBLISHED,
  GRAD_STUDENT_API_NOTIFIED,
  MYED_NOTIFIED,
  COMPLETION_DATE_SET,
  SAGA_COMPLETED,
  STUDENT_ALREADY_EXIST,
  MERGE_FOUND,
  STUDENTS_FOUND,
  ASSESSMENT_STUDENT_UPDATED,
  SCHOOL_OF_RECORD_UPDATED,
  XAM_FILES_GENERATED_AND_UPLOADED,
  READ_STUDENT_RESULT_FOR_PROCESSING_SUCCESS,
  STUDENT_RESULT_CREATED,
  STUDENT_NOT_FOUND,
  STAGED_STUDENTS_MARKED_READY_FOR_TRANSFER,
  STUDENT_TRANSFER_PROCESSED,
  STUDENT_DOAR_CALCULATED,
  GRAD_STATUS_UPDATED,
  MERGE_CREATED,
  DEM_STUDENT_PROCESSED_IN_GRAD_STUDENT_API,
  READ_TRANSFER_STUDENT_RESULT_SUCCESS
}
