package ca.bc.gov.educ.assessment.api.constants;


public enum TopicsEnum {
  STUDENT_ASSESSMENT_API_TOPIC,
  INSTITUTE_API_TOPIC,
  STUDENT_ASSESSMENT_EVENTS_TOPIC,
  PEN_SERVICES_API_TOPIC,
  PUBLISH_STUDENT_REGISTRATION_TOPIC,
  PUBLISH_STUDENT_REGISTRATION_SAGA_TOPIC,
  STUDENT_API_TOPIC
}
