package ca.bc.gov.educ.assessment.api.constants;


public enum TopicsEnum {
  STUDENT_ASSESSMENT_API_TOPIC,
  INSTITUTE_API_TOPIC,
  STUDENT_ASSESSMENT_EVENTS_TOPIC,
  PEN_SERVICES_EVENTS_TOPIC,
  GRAD_STUDENT_API_FETCH_GRAD_STUDENT_TOPIC,
  PUBLISH_STUDENT_REGISTRATION_TOPIC,
  PUBLISH_STUDENT_REGISTRATION_SAGA_TOPIC,
  STUDENT_API_TOPIC,
  XAM_FILE_GENERATION_TOPIC,
  READ_STUDENT_RESULT_RECORD,
  PROCESS_STUDENT_RESULT_SAGA_TOPIC,
  STUDENT_TRANSFER_PROCESSING_TOPIC
}
