package ca.bc.gov.educ.eas.api.constants;

/**
 * The enum Event outcome.
 */
public enum EventOutcome {
  INITIATE_SUCCESS,
  STUDENT_REGISTRATION_FOUND,
  STUDENT_REGISTRATION_NOT_FOUND,
  SESSIONS_FOUND,
  STUDENT_REGISTRATION_EVENT_READ,
  STUDENT_REGISTRATION_PUBLISHED,
  SAGA_COMPLETED,
  STUDENT_ALREADY_EXIST,
  MERGE_FOUND
}
