package ca.bc.gov.educ.eas.api.constants;


public enum TopicsEnum {
  EAS_API_TOPIC,
  INSTITUTE_API_TOPIC,
  EAS_EVENTS_TOPIC,
  PEN_SERVICES_API_TOPIC,
  PUBLISH_STUDENT_REGISTRATION_TOPIC,
  PUBLISH_STUDENT_REGISTRATION_SAGA_TOPIC,
  STUDENT_API_TOPIC
}
